[build]
builder = "DOCKERFILE"
dockerfilePath = "./Execution_Service/Dockerfile"

[deploy]
startCommand = "node index.js"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
